### ISSUE TITLE
Error: gnupg

### ISSUE THREAD

**Issue by ldod-lle** [Secure-Compliance-Solutions-LLC/GVM-Docker#17]
Getting this trying to start the container:
```

Creating gnupg folder...


mv: cannot stat '/usr/local/var/lib/gvm/gvmd/gnupg': No such file or directory
```
This is as of the last release 21 hours ago.

**Comment by pixelsquared** [comment]
I am working on this issue right now should be fixed in a few hours.

**Comment by pixelsquared** [comment]
I believe I have fixed the issue. Could you pull the newest version of the container and verify?

**Comment by ldod-lle** [comment]
Ok web interface launches, but unable to login w/message "GMP service is down". Process listing still shows ./start.sh still executing. I tried to install strace but I'd have to tweak sysctl to see what it's hung on.  :frowning_face:

**Comment by pixelsquared** [comment]
Could you create a new issue with logs from the container?
